# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild + Cppcheck

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Cppcheck
      run: choco install cppcheck

    - name: Run cppcheck
      shell: pwsh
      run: |
        & "C:\Program Files\Cppcheck\cppcheck.exe" --enable=all --inconclusive --std=c++23 --platform=win64 --suppress=missingIncludeSystem --inline-suppr --check-level=exhaustive --force . 2> cppcheck.txt
        Get-Content cppcheck.txt

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Debug Solution
      run: msbuild Civ_Rob_2.0.sln /p:Configuration=Debug /p:Platform=x64

    - name: Build Release Solution
      run: msbuild Civ_Rob_2.0.sln /p:Configuration=Release /p:Platform=x64

